"""create table Credentials

Revision ID: 0701e809039b
Revises: e0ecf172f5a8
Create Date: 2023-01-31 22:16:04.382027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0701e809039b'
down_revision = 'e0ecf172f5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('private_key_id', sa.String(length=120), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('client_email', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.String(length=120), nullable=False),
    sa.Column('auth_uri', sa.String(length=120), nullable=False),
    sa.Column('token_uri', sa.String(length=120), nullable=False),
    sa.Column('auth_provider_x509_cert_url', sa.String(length=120), nullable=False),
    sa.Column('client_x509_cert_url', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    op.drop_table('credentials')
    # ### end Alembic commands ###
