common:
  port: 8080 # порт, на котором будет запускаться наше приложение
postgres:
  database_url: postgres://postgres:postgres@localhost/aiohttp
  require_ssl: false # стоит ли шифровать соединение с базой